language: node_js
node_js:
  - node
cache: npm

install:
  - npm ci

script:
  - npm test

deploy:
  skip-cleanup: true
  github-token: $GITHUB-TOKEN
  on:
    branch: develop
  app:
    develop: howmies-api
  provider: heroku
  api_key: HEROKU_TOKEN
